### ISSUE TITLE
Multiple add key

### ISSUE THREAD

**Issue by goper-leo** [simoebenhida/vue-tags#2]
How about adding multiple add keys. Example using **enter** or **comma** `add-key="13|188"` . Thanks.

**Comment by simoebenhida** [comment]
Oh yes that is a good idea i will add to the list thank you

**Comment by itsrishabh** [comment]
+1 - was trying to do this today as well haha -- i think an array makes more sense as opposed to a pipe which is used for filter.

ie: `[188, 13]` :)

**Comment by simoebenhida** [comment]
@itsrishabh @goper-leo check this pull request #4 is it what we are looking for ?
